# Generated by Django 5.0.1 on 2024-01-09 02:35

import django_jalali.db.models
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('create', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('phone', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False, null=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, default='1.jpg', null=True, upload_to='user')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
