# Generated by Django 5.0.1 on 2024-01-11 06:03

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='1.jpg', null=True, upload_to='user/'),
        ),
    ]
