# Generated by Django 5.0.1 on 2024-01-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='create',
            new_name='created',
        ),
    ]
