# Generated by Django 5.0.1 on 2024-01-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_size_varrient_varrient_name_delete_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='varrient',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='blue-jean', unique=True),
            preserve_default=False,
        ),
    ]
