# Generated by Django 5.0.1 on 2024-01-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_varrient_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
    ]
