# Generated by Django 5.0.1 on 2024-01-30 08:59

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='pay_datetime',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
