# Generated by Django 5.0.1 on 2024-01-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_comment_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varrient',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='سسس', unique=True),
            preserve_default=False,
        ),
    ]
