# Generated by Django 5.0.1 on 2024-01-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_varrient_slug_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
