# Generated by Django 5.0.1 on 2024-01-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_p_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_view',
        ),
    ]
