# Generated by Django 5.0.1 on 2024-01-31 09:07

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_product_p_view'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('payment', models.PositiveIntegerField()),
                ('sum_factory_price', models.PositiveIntegerField(blank=True, null=True)),
                ('sum_unit_price', models.PositiveIntegerField(blank=True, null=True)),
                ('sum_total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('sum_total_profit', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_factors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FactorItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_price', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('factory_profit', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit_profit', models.PositiveIntegerField()),
                ('total_profit', models.PositiveIntegerField()),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_items', to='product.factor')),
                ('item_var', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.varrient')),
            ],
        ),
    ]
