# Generated by Django 5.0.1 on 2024-01-31 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_factor_factoritems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factoritems',
            name='factory_profit',
        ),
        migrations.AddField(
            model_name='factor',
            name='card',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='product.card'),
            preserve_default=False,
        ),
    ]
