# Generated by Django 5.0.1 on 2024-02-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_is_payed_card_is_paid_alter_card_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.PositiveIntegerField()),
            ],
        ),
    ]
