# Generated by Django 5.0.1 on 2024-02-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_factor_sum_factory_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='transfer',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
