# Generated by Django 5.0.1 on 2024-02-05 12:57

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_factoritems_item_var_factoritems_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='created',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
