# Generated by Django 5.0.1 on 2024-02-05 13:11

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_factor_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
